name: kumaconda22
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _py-xgboost-mutex=2.0=cpu_0
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py39h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - albumentations=1.2.0=pyhd8ed1ab_0
  - alembic=1.7.5=pyhd3eb1b0_1
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - atk-1.0=2.36.0=h28cd5cc_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopage=0.5.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py39h06a4308_0
  - blosc=1.21.0=h8c45485_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=he6710b0_2
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hf32fb01_1
  - catboost=1.0.6=py39hf3d152e_1
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py39hd667e15_1
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cliff=3.10.1=pyhd8ed1ab_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=2.3.3=py39hf3d152e_1
  - colorama=0.4.5=py39h06a4308_0
  - colorlog=5.0.1=py39h06a4308_1
  - cryptography=37.0.1=py39h9ce1e76_0
  - cuda=11.6.2=h8144a35_0
  - cuda-cccl=11.7.58=hc415cf5_0
  - cuda-command-line-tools=11.7.0=0
  - cuda-compiler=11.7.0=0
  - cuda-cudart=11.7.60=h9538e0e_0
  - cuda-cudart-dev=11.7.60=h6a7c232_0
  - cuda-cuobjdump=11.7.50=h28cc80a_0
  - cuda-cupti=11.7.50=hb6f9eaf_0
  - cuda-cuxxfilt=11.7.50=hb365495_0
  - cuda-driver-dev=11.7.60=0
  - cuda-gdb=11.7.50=h4a0ac72_0
  - cuda-libraries=11.7.0=0
  - cuda-libraries-dev=11.7.0=0
  - cuda-memcheck=11.7.50=hc446b2b_0
  - cuda-nvcc=11.7.64=0
  - cuda-nvdisasm=11.7.50=h5bd0695_0
  - cuda-nvml-dev=11.7.50=h3af1343_0
  - cuda-nvprof=11.7.50=h7a2404d_0
  - cuda-nvprune=11.7.50=h7add7b4_0
  - cuda-nvrtc=11.7.50=hd0285e0_0
  - cuda-nvrtc-dev=11.7.50=heada363_0
  - cuda-nvtx=11.7.50=h05b0816_0
  - cuda-nvvp=11.7.50=hd2289d5_0
  - cuda-runtime=11.7.0=0
  - cuda-sanitizer-api=11.7.50=hb424887_0
  - cuda-toolkit=11.7.0=0
  - cuda-tools=11.7.0=0
  - cuda-visual-tools=11.7.0=0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2022.5.0=py39h06a4308_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - eigen=3.4.0=h4bd325d_0
  - entrypoints=0.4=py39h06a4308_0
  - et_xmlfile=1.0.1=py_1001
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3.2=hca11adc_0
  - fftw=3.3.9=h27cfd23_1
  - filelock=3.9.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.2.0=py39h7f8727e_0
  - fsspec=2022.3.0=py39h06a4308_0
  - g-ir-build-tools=1.68.0=py39haf67bb6_2
  - g-ir-host-tools=1.68.0=hc194b35_2
  - gdcm=2.8.9=py39h1f6dd6f_5
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.21.0=hf68c758_0
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.1=h7b6447c_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.68.0=py39h2109141_1
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.47.1=hebd9034_0
  - greenlet=1.1.1=py39h295c915_0
  - grpcio=1.42.0=py39hce63b2e_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.18.5=h76c114f_0
  - gstreamer-orc=0.4.32=h7f98852_1
  - gtk2=2.24.33=hab0c2f8_0
  - gts=0.7.6=h08bb679_0
  - h5py=3.7.0=py39h737f45e_0
  - harfbuzz=2.7.2=ha5b49bf_1
  - hdf5=1.10.6=h3ffc7dd_1
  - huggingface_hub=0.11.1=pyhd8ed1ab_0
  - humanize=4.2.3=pyhd8ed1ab_0
  - icu=67.1=he1b5a44_0
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py39h4cda21f_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagemagick=7.0.10_28=pl5262hfcab4aa_3
  - importlib-metadata=4.11.3=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py39h06a4308_0
  - ipython=8.4.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jasper=1.900.1=hd497a04_4
  - jbig=2.1=hdba287a_0
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - json-c=0.16=hc379101_0
  - jsonschema=4.4.0=py39h06a4308_0
  - jupyter=1.0.0=py39hf3d152e_7
  - jupyter_client=7.2.2=py39h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcublas=11.10.1.25=he442b6f_0
  - libcublas-dev=11.10.1.25=h0c8ac2b_0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufft-dev=10.7.2.124=h98a8f43_0
  - libcurand=10.2.10.50=heec50f7_0
  - libcurand-dev=10.2.10.50=hd49a9cd_0
  - libcurl=7.82.0=h0b77cf5_0
  - libcusolver=11.3.5.50=hcab339c_0
  - libcusolver-dev=11.3.5.50=hc6eba6f_0
  - libcusparse=11.7.3.50=h6aaafad_0
  - libcusparse-dev=11.7.3.50=hc644b96_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libexif=0.6.21=h7f98852_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgirepository=1.68.0=h7771c88_2
  - libglib=2.68.4=h3e27bee_0
  - libgsf=1.14.47=h88be47d_3
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libitk=5.1.2=h86d312b_0
  - libitk-devel=5.1.2=h9c3ff4c_0
  - libjpeg-turbo=2.1.3=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h3826bc1_1
  - libmatio=1.5.21=h9e294dc_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.7.3.21=h3effbd9_0
  - libnpp-dev=11.7.3.21=hb6476a9_0
  - libnvjpeg=11.7.2.34=hfe236c7_0
  - libnvjpeg-dev=11.7.2.34=h2e48410_0
  - libopencv=4.5.2=py39h2406f9b_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.15.8=h780b84a_1
  - librsvg=2.50.3=hfa39831_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libtool=2.4.6=h295c915_1008
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvips=8.10.5=h1a5f05f_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxgboost=1.5.1=cpu_h3d145d1_2
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h68273f3_2
  - libzlib=1.2.12=h166bdaf_2
  - libzopfli=1.0.3=he6710b0_0
  - lightgbm=3.3.2=py39he80948d_0
  - llvm-openmp=14.0.4=he0ac6c6_0
  - llvmlite=0.36.0=py39h612dafd_4
  - locket=1.0.0=py39h06a4308_0
  - lz4-c=1.9.3=h295c915_1
  - mako=1.1.4=pyhd3eb1b0_0
  - markdown=3.3.4=py39h06a4308_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-base=3.5.1=py39ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=5.2.0=py39h7f8727e_2
  - munch=2.5.0=py_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.25=ha770c72_0
  - mysql-libs=8.0.25=h935591d_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.4.4=py39h06a4308_0
  - nbformat=5.3.0=py39h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - nibabel=4.0.1=pyhd8ed1ab_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - notebook=6.4.11=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numba=0.53.1=py39ha9443f7_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpy=1.23.1=py39h6c91a56_0
  - numpy-base=1.23.1=py39ha15fc14_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.2=py39hf3d152e_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openslide=3.4.1=h978ee9a_3
  - openssl=1.1.1s=h0b41bf4_1
  - optuna=2.10.1=pyhd8ed1ab_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py39h6a678d5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.42.4=h69149e4_5
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patsy=0.5.2=py39h06a4308_1
  - pbr=5.6.0=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - perl=5.26.2=h14c3975_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hace64e9_0
  - pip=22.1.2=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkg-config=0.29.2=h1bed415_8
  - plotly=5.6.0=pyhd3eb1b0_0
  - poppler=0.89.0=h2de54a5_5
  - poppler-data=0.4.11=h06a4308_0
  - pretrainedmodels=0.7.4=pyhd8ed1ab_2
  - prettytable=3.3.0=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.15.8=py39he80948d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.5.2=py39hef51801_0
  - py-xgboost=1.5.1=cpu_py39h4655687_2
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydicom=2.3.0=pyh6c4a22f_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39h06a4308_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyqt=5.12.3=py39h03dd644_4
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-graphviz=0.16=pyhd3eb1b0_1
  - python_abi=3.9=2_cp39
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvips=2.1.8=py39h07f9747_1
  - pywavelets=1.3.0=py39h7f8727e_0
  - pyyaml=6.0=py39h7f8727e_1
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt=5.12.9=h763d07f_1
  - qtconsole=5.3.1=py39h06a4308_0
  - qtconsole-base=5.3.1=pyha770c72_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - qudida=0.0.4=pyhd8ed1ab_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py39h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.19.2=py39hde0f152_0
  - scikit-learn=1.0.2=py39h51133e4_1
  - scipy=1.9.1=py39h14f4228_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py39h06a4308_0
  - simpleitk=2.0.2=py39h156e488_1
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlalchemy=1.4.32=py39h7f8727e_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.2=py39hd257fcd_0
  - stevedore=3.5.0=py39hf3d152e_3
  - tbb=2020.3=hfd86e86_0
  - tenacity=8.0.1=py39h06a4308_0
  - tensorboard=2.9.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py39_cu113
  - torchio=0.18.30=pyhd8ed1ab_0
  - torchvision=0.12.0=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - tslearn=0.5.2=py39hce5d2b2_1
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - wrapt=1.14.1=py39hb9d737c_0
  - x264=1!161.3030=h7f98852_1
  - xgboost=1.5.1=cpu_py39h4655687_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py39h27cfd23_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.8.0=py39h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - japanize-matplotlib==1.1.3
    - kaggle==1.5.12
    - opencv-python==4.6.0.66
    - pylibjpeg==1.4.0
    - pylibjpeg-libjpeg==1.3.1
    - pylibjpeg-openjpeg==1.2.1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - python-slugify==6.1.2
    - text-unidecode==1.3
    - torch-summary==1.4.5
    - volumentations-3d==1.0.4
